baseURL = 'https://chgk-in-finland-draft.netlify.app/'
languageCode = 'ru'
defaultContentLanguage = 'ru'
title = 'Ğ§Ğ“Ğš Ğ² Ğ¤Ğ¸Ğ½Ğ»ÑĞ½Ğ´Ğ¸Ğ¸. ĞšĞ»ÑƒĞ± Â«Ğ–ĞµĞ¼Ñ‡ÑƒĞ¶Ğ½Ğ°Ñ ÑĞ¾Ğ²Ğ°Â» (Ñ‡ĞµÑ€Ğ½Ğ¾Ğ²Ğ¸Ğº)'
theme = 'PaperMod'
copyright = 'Made with ğŸ–¤ by [salmiakki](https://github.com/salmiakki/chgk_helsinki_site)'
enableGitInfo = true

[markup.goldmark.renderer]
unsafe = true